name: "npm Publish Latest Tag"
author: "tobysmith568"
description: "Returns a tag for you to supply to the npm publish command so that updates to old major versions don't automatically get given the 'latest' tag"
inputs:
  package-json:
    description: "Location of the package.json file relative to the repo root"
    required: true
    default: "./package.json"
outputs:
  latest-tag:
    description: "The value of the 'latest' tag to use when publishing"
runs:
  using: "node16"
  main: "./dist-action/index.js'