name: 'build-test'
on: 
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - working-directory: ./core
        run : npm ci
      - working-directory: ./core
        run : npm run build
      - working-directory: ./core
        run : npm run test:ci

      - run: npm ci
      - run: npm run build
      - run: npm run test:ci

  e2e-higher-patch-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        id: subject
        with:
          package-json: './e2e/higher-patch-version/package.json'
      - shell: pwsh
        run: 'exit ("${{ steps.subject.outputs.latestTag }}" -eq "latest" ? 0 : 1)'

  e2e-higher-minor-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        id: subject
        with:
          package-json: './e2e/higher-minor-version/package.json'
      - shell: pwsh
        run: 'exit ("${{ steps.subject.outputs.latestTag }}" -eq "latest" ? 0 : 1)'

  e2e-higher-major-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        id: subject
        with:
          package-json: './e2e/higher-major-version/package.json'
      - shell: pwsh
        run: 'exit ("${{ steps.subject.outputs.latestTag }}" -eq "latest" ? 0 : 1)'

  e2e-higher-patch-version-than-v1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        id: subject
        with:
          package-json: './e2e/higher-patch-version-than-v1/package.json'
      - shell: pwsh
        run: 'exit ("${{ steps.subject.outputs.latestTag }}" -eq "latest-1" ? 0 : 1)'

  e2e-higher-minor-version-than-v1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        id: subject
        with:
          package-json: './e2e/higher-minor-version-than-v1/package.json'
      - shell: pwsh
        run: 'exit ("${{ steps.subject.outputs.latestTag }}" -eq "latest-1" ? 0 : 1)'

  e2e-lower-major-version-than-all:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        id: subject
        with:
          package-json: './e2e/lower-major-version-than-all/package.json'
      - shell: pwsh
        run: 'exit ("${{ steps.subject.outputs.latestTag }}" -eq "latest-0" ? 0 : 1)'

  e2e-does-not-exist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        id: subject
        with:
          package-json: './e2e/does-not-exist/package.json'
      - shell: pwsh
        run: 'exit ("${{ steps.subject.outputs.latestTag }}" -eq "latest" ? 0 : 1)'

  e2e-invalid-path:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        continue-on-error: true
        id: subject
        with:
          package-json: './e2e/package.json-does-not-exist'
      - if: always()
        shell: pwsh
        run: 'exit ("${{ steps.subject.outputs.latestTag }}" -eq "" ? 0 : 1)'
